### ISSUE TITLE
Poke16 Writes only the first 8 bits

### ISSUE THREAD

**Issue by Kuumba123** [JonathanDotCel/NOTPSXSerial#13]
poke8 and 32 work just fine but for some reason only the 1st 8-bits of Poke-16 seem to work (I double checked using /dump)

**Comment by johnbaumann** [comment]
> poke8 and 32 work just fine but for some reason only the 1st 8-bits of Poke-16 seem to work (I double checked using /dump)

I can check this out, but I'll need the address you're trying to poke to verify some things.

**Comment by Kuumba123** [comment]
sure thing , I was trying to edit the water level in MegaMan 8 (the lower the value the higher the water level is) normally the game disables the water by writting 0x7FFF
nops /poke16 0x801b2988 0x7FFF COM5

**Comment by johnbaumann** [comment]
> 

Thanks for that. I was able to track down and correct this problem, good news is that it was on the pc side. Grab the latest nops and let me know if this isn't resolved for some reason.

**Comment by Kuumba123** [comment]
yup works perfectly !
