### ISSUE TITLE
Please add optional filename argument for /dump

### ISSUE THREAD

**Issue by T0fuZ** [JonathanDotCel/NOTPSXSerial#6]
This is so awesome tool I have no words. I created serial cable and now having fun with patching games on  the fly.
I do have one small feature request:
Is it possible to add optional filename argument for /dump option, and effectively be able to override that file if its presented. This is for scripted dumps.

Also: are you planning pc fileserver and STDIN functionality in monitor mode?

EDIT: never mind about STDIN, I can see from code that should even work. Will attempt to build this. You accept pullrequests? I could try to do add optional filename for /dump. I recently started with C# and should be cool challenge and I really want to help

**Comment by JonathanDotCel** [comment]
Hah, go for it!
Gimme a shout on the psxdev discord if you want to go through it.

Just a thought: might be a good idea to have it *always* expect a filename to simplify the code.
Then perhaps you could use `*` to auto-generate the file name.
